package com.saveapenny.stock.domain;

import com.fasterxml.jackson.annotation.JsonAlias;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)
public record CompanyOverview(
        @JsonAlias("Symbol") String symbol,
        @JsonAlias("AssetType") String assetType,
        @JsonAlias("Name") String name,
        @JsonAlias("Description") String description,
        @JsonAlias("CIK") String cik,
        @JsonAlias("Exchange") String exchange,
        @JsonAlias("Currency") String currency,
        @JsonAlias("Country") String country,
        @JsonAlias("Sector") String sector,
        @JsonAlias("Industry") String industry,
        @JsonAlias("Address") String address,
        @JsonAlias("FiscalYearEnd") String fiscalYearEnd,
        @JsonAlias("LatestQuarter") String latestQuarter,
        @JsonAlias("MarketCapitalization") String marketCapitalization,
        @JsonAlias("EBITDA") String ebitda,
        @JsonAlias("PERatio") String peRatio,
        @JsonAlias("PEGRatio") String pegRatio,
        @JsonAlias("BookValue") String bookValue,
        @JsonAlias("DividendPerShare") String dividendPerShare,
        @JsonAlias("DividendYield") String dividendYield,
        @JsonAlias("EPS") String eps,
        @JsonAlias("RevenuePerShareTTM") String revenuePerShareTTM,
        @JsonAlias("ProfitMargin") String profitMargin,
        @JsonAlias("OperatingMarginTTM") String operatingMarginTTM,
        @JsonAlias("ReturnOnAssetsTTM") String returnOnAssetsTTM,
        @JsonAlias("ReturnOnEquityTTM") String returnOnEquityTTM,
        @JsonAlias("RevenueTTM") String revenueTTM,
        @JsonAlias("GrossProfitTTM") String grossProfitTTM,
        @JsonAlias("DilutedEPSTTM") String dilutedEpsTTM,
        @JsonAlias("QuarterlyEarningsGrowthYOY") String quarterlyEarningsGrowthYOY,
        @JsonAlias("QuarterlyRevenueGrowthYOY") String quarterlyRevenueGrowthYOY,
        @JsonAlias("AnalystTargetPrice") String analystTargetPrice,
        @JsonAlias("AnalystRatingStrongBuy") String analystRatingStrongBuy,
        @JsonAlias("AnalystRatingBuy") String analystRatingBuy,
        @JsonAlias("AnalystRatingHold") String analystRatingHold,
        @JsonAlias("AnalystRatingSell") String analystRatingSell,
        @JsonAlias("AnalystRatingStrongSell") String analystRatingStrongSell,
        @JsonAlias("TrailingPE") String trailingPE,
        @JsonAlias("ForwardPE") String forwardPE,
        @JsonAlias("PriceToSalesRatioTTM") String priceToSalesRatioTTM,
        @JsonAlias("PriceToBookRatio") String priceToBookRatio,
        @JsonAlias("EVToRevenue") String evToRevenue,
        @JsonAlias("EVToEBITDA") String evToEBITDA,
        @JsonAlias("Beta") String beta,
        @JsonAlias("52WeekHigh") String weekHigh52,
        @JsonAlias("52WeekLow") String weekLow52,
        @JsonAlias("50DayMovingAverage") String movingAverage50Day,
        @JsonAlias("200DayMovingAverage") String movingAverage200Day,
        @JsonAlias("SharesOutstanding") String sharesOutstanding,
        @JsonAlias("DividendDate") String dividendDate,
        @JsonAlias("ExDividendDate") String exDividendDate,
        @JsonAlias("Error Message") String errorMessage,
        @JsonAlias("Note") String note) {

    public CompanyOverview(
            String symbol,
            String assetType,
            String name,
            String description,
            String cik,
            String exchange,
            String currency,
            String country,
            String sector,
            String industry,
            String address,
            String fiscalYearEnd,
            String latestQuarter,
            String marketCapitalization,
            String ebitda,
            String peRatio,
            String pegRatio,
            String bookValue,
            String dividendPerShare,
            String dividendYield,
            String eps,
            String revenuePerShareTTM,
            String profitMargin,
            String operatingMarginTTM,
            String returnOnAssetsTTM,
            String returnOnEquityTTM,
            String revenueTTM,
            String grossProfitTTM,
            String dilutedEpsTTM,
            String quarterlyEarningsGrowthYOY,
            String quarterlyRevenueGrowthYOY,
            String analystTargetPrice,
            String analystRatingStrongBuy,
            String analystRatingBuy,
            String analystRatingHold,
            String analystRatingSell,
            String analystRatingStrongSell,
            String trailingPE,
            String forwardPE,
            String priceToSalesRatioTTM,
            String priceToBookRatio,
            String evToRevenue,
            String evToEBITDA,
            String beta,
            String weekHigh52,
            String weekLow52,
            String movingAverage50Day,
            String movingAverage200Day,
            String sharesOutstanding,
            String dividendDate,
            String exDividendDate) {
        this(
                symbol,
                assetType,
                name,
                description,
                cik,
                exchange,
                currency,
                country,
                sector,
                industry,
                address,
                fiscalYearEnd,
                latestQuarter,
                marketCapitalization,
                ebitda,
                peRatio,
                pegRatio,
                bookValue,
                dividendPerShare,
                dividendYield,
                eps,
                revenuePerShareTTM,
                profitMargin,
                operatingMarginTTM,
                returnOnAssetsTTM,
                returnOnEquityTTM,
                revenueTTM,
                grossProfitTTM,
                dilutedEpsTTM,
                quarterlyEarningsGrowthYOY,
                quarterlyRevenueGrowthYOY,
                analystTargetPrice,
                analystRatingStrongBuy,
                analystRatingBuy,
                analystRatingHold,
                analystRatingSell,
                analystRatingStrongSell,
                trailingPE,
                forwardPE,
                priceToSalesRatioTTM,
                priceToBookRatio,
                evToRevenue,
                evToEBITDA,
                beta,
                weekHigh52,
                weekLow52,
                movingAverage50Day,
                movingAverage200Day,
                sharesOutstanding,
                dividendDate,
                exDividendDate,
                null,
                null);
    }
}
